### ISSUE TITLE
repost, show are failing while post, delete working fine 

### ISSUE THREAD

**Issue by andrew521** [guoarthur/Kijiji-Repost-Headless#20]
Same for repost_folder (not working) and folder (working) commands.

[root@centos7 battery.01]# python3.6 /root/Kijiji-Repost/Kijiji-Repost-Headless-master/kijiji_repost_headless/kijiji_cmd.py -u uuuuuuuuu -p ppppppp repost myAd.inf
Traceback (most recent call last):
  File "/root/Kijiji-Repost/Kijiji-Repost-Headless-master/kijiji_repost_headless/kijiji_cmd.py", line 134, in <module>
    main()
  File "/root/Kijiji-Repost/Kijiji-Repost-Headless-master/kijiji_repost_headless/kijiji_cmd.py", line 55, in main
    args.function(args)
  File "/root/Kijiji-Repost/Kijiji-Repost-Headless-master/kijiji_repost_headless/kijiji_cmd.py", line 112, in repost_ad
    api.delete_ad_using_title(delAdName)
  File "/root/Kijiji-Repost/Kijiji-Repost-Headless-master/kijiji_repost_headless/kijiji_api.py", line 118, in delete_ad_using_title
    allAds = self.get_all_ads()
  File "/root/Kijiji-Repost/Kijiji-Repost-Headless-master/kijiji_repost_headless/kijiji_api.py", line 160, in get_all_ads
    myAdsTree = json.loads(myAdsPage.text)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[ad deleted manually in between]

[root@centos7 battery.01]# python3.6 /root/Kijiji-Repost/Kijiji-Repost-Headless-master/kijiji_repost_headless/kijiji_cmd.py -u uuuuuuuuu -p ppppppp post myAd.inf
Image Upload success on try #1
[root@centos7 battery.01]# python3.6 /root/Kijiji-Repost/Kijiji-Repost-Headless-master/kijiji_repost_headless/kijiji_cmd.py -u uuuuuuuuu -p ppppppp show
Traceback (most recent call last):
  File "/root/Kijiji-Repost/Kijiji-Repost-Headless-master/kijiji_repost_headless/kijiji_cmd.py", line 134, in <module>
    main()
  File "/root/Kijiji-Repost/Kijiji-Repost-Headless-master/kijiji_repost_headless/kijiji_cmd.py", line 55, in main
    args.function(args)
  File "/root/Kijiji-Repost/Kijiji-Repost-Headless-master/kijiji_repost_headless/kijiji_cmd.py", line 90, in show_ads
    [print("{} '{}'".format(adId, adName)) for adName, adId in api.get_all_ads()]
  File "/root/Kijiji-Repost/Kijiji-Repost-Headless-master/kijiji_repost_headless/kijiji_api.py", line 160, in get_all_ads
    myAdsTree = json.loads(myAdsPage.text)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[root@centos7 battery.01]#

**Comment by andrew521** [comment]
nuke does not work as well. It looks like kikiji's json repose has been changed and parsing is failing.

**Comment by guoarthur** [comment]
Would you like to attempt to fix this and by submitting a pull request?

**Comment by guoarthur** [comment]
Should be fixed now. Please let me know if there are any issues.

**Comment by andrew521** [comment]
tested show and repost_folder, both working fine, thanks.
