### ISSUE TITLE
Can't post ad as of this afternoon (was working this morning), but can log in and show existing ads, delete, etc

### ISSUE THREAD

**Issue by vipertemp** [guoarthur/Kijiji-Repost-Headless#32]
Did something in the back-end change? The code was working 100% as of this morning, but when I came back this afternoon I am no longer able to post ads, only delete them, or show them. I changed nothing whatsoever on my side.

In `upload_one_image(imgFile)`, the value of `r.status_code` is 401 and not 200 and the error is thrown.
Error 401 is "Unauthorized: Access is denied due to invalid credentials"

Yet clearly I can log in and show my ads, or delete them through the API, as well as manually, with the exact same credential info. Earlier on I did try to post to another account (and `rememberMe` in `login(self, username, password)` is set to True and also on. I wonder if there's some conflict with a cookie or something? I admit, I don't really know what I'm talking about, here, and defer to your expertise.

Is anyone else having problems posting?

**Comment by andrew521** [comment]
Similar issue here (it was working fine at 9am and failed at 5pm)

$ python3.6 /root/Kijiji-Repost/Kijiji-Repost-Headless-master/kijiji_repost_headless/kijiji_cmd.py      folder some-folder
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/root/Kijiji-Repost/Kijiji-Repost-Headless-master/kijiji_repost_headless/kijiji_api.py", line 56, in upload_one_image
    raise PostAdException(r.text)
kijiji_api.PostAdException: Could not post ad.

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/Kijiji-Repost/Kijiji-Repost-Headless-master/kijiji_repost_headless/kijiji_cmd.py", line 134, in <module>
    main()
  File "/root/Kijiji-Repost/Kijiji-Repost-Headless-master/kijiji_repost_headless/kijiji_cmd.py", line 55, in main
    args.function(args)
  File "/root/Kijiji-Repost/Kijiji-Repost-Headless-master/kijiji_repost_headless/kijiji_cmd.py", line 79, in post_folder
    post_ad(args)
  File "/root/Kijiji-Repost/Kijiji-Repost-Headless-master/kijiji_repost_headless/kijiji_cmd.py", line 85, in post_ad
    api.post_ad_using_data(data, imageFiles)
  File "/root/Kijiji-Repost/Kijiji-Repost-Headless-master/kijiji_repost_headless/kijiji_api.py", line 133, in post_ad_using_data
    imageList = self.upload_image(imageFiles)
  File "/root/Kijiji-Repost/Kijiji-Repost-Headless-master/kijiji_repost_headless/kijiji_api.py", line 126, in upload_image
    images = p.map(upload_one_image, imageFiles)
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 608, in get
    raise self._value
kijiji_api.PostAdException: Could not post ad.

**Comment by andrew521** [comment]
It is working for me. Thank you for the quick fix.

**Comment by vipertemp** [comment]
It was working again after your fixes this morning, but the Error 401 is back as of now.
