### ISSUE TITLE
Random 401 on uploading images

### ISSUE THREAD

**Issue by orditeck** [guoarthur/Kijiji-Repost-Headless#37]
See log below.

I just re-do the same command line over & over until it works.

```
➜  kijiji_repost_headless git:(master) ✗ python3 kijiji_cmd.py folder seadoo      
401

Traceback (most recent call last):
  File "kijiji_cmd.py", line 155, in <module>
    main()
  File "kijiji_cmd.py", line 48, in main
    args.function(args)
  File "kijiji_cmd.py", line 79, in post_folder
    post_ad(args)
  File "kijiji_cmd.py", line 88, in post_ad
    api.post_ad_using_data(data, imageFiles)
  File "/Users/userremoved/Downloads/Kijiji-Repost-Headless/kijiji_repost_headless/kijiji_api.py", line 155, in post_ad_using_data
    imageList = self.upload_image(image_upload_token, imageFiles)
  File "/Users/userremoved/Downloads/Kijiji-Repost-Headless/kijiji_repost_headless/kijiji_api.py", line 133, in upload_image
    imageTree = json.loads(r.text)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
➜  kijiji_repost_headless git:(master) ✗ python3 kijiji_cmd.py folder seadoo
401

Traceback (most recent call last):
  File "kijiji_cmd.py", line 155, in <module>
    main()
  File "kijiji_cmd.py", line 48, in main
    args.function(args)
  File "kijiji_cmd.py", line 79, in post_folder
    post_ad(args)
  File "kijiji_cmd.py", line 88, in post_ad
    api.post_ad_using_data(data, imageFiles)
  File "/Users/userremoved/Downloads/Kijiji-Repost-Headless/kijiji_repost_headless/kijiji_api.py", line 155, in post_ad_using_data
    imageList = self.upload_image(image_upload_token, imageFiles)
  File "/Users/userremoved/Downloads/Kijiji-Repost-Headless/kijiji_repost_headless/kijiji_api.py", line 133, in upload_image
    imageTree = json.loads(r.text)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
➜  kijiji_repost_headless git:(master) ✗ 
➜  kijiji_repost_headless git:(master) ✗ 
➜  kijiji_repost_headless git:(master) ✗ 
➜  kijiji_repost_headless git:(master) ✗ 
➜  kijiji_repost_headless git:(master) ✗ 
➜  kijiji_repost_headless git:(master) ✗ python3 kijiji_cmd.py folder seadoo
401

Traceback (most recent call last):
  File "kijiji_cmd.py", line 155, in <module>
    main()
  File "kijiji_cmd.py", line 48, in main
    args.function(args)
  File "kijiji_cmd.py", line 79, in post_folder
    post_ad(args)
  File "kijiji_cmd.py", line 88, in post_ad
    api.post_ad_using_data(data, imageFiles)
  File "/Users/userremoved/Downloads/Kijiji-Repost-Headless/kijiji_repost_headless/kijiji_api.py", line 155, in post_ad_using_data
    imageList = self.upload_image(image_upload_token, imageFiles)
  File "/Users/userremoved/Downloads/Kijiji-Repost-Headless/kijiji_repost_headless/kijiji_api.py", line 133, in upload_image
    imageTree = json.loads(r.text)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
➜  kijiji_repost_headless git:(master) ✗ 
➜  kijiji_repost_headless git:(master) ✗ 
➜  kijiji_repost_headless git:(master) ✗ 
➜  kijiji_repost_headless git:(master) ✗ 
➜  kijiji_repost_headless git:(master) ✗ 
➜  kijiji_repost_headless git:(master) ✗ python3 kijiji_cmd.py folder seadoo
{"status":"OK","normalUrl":"https://i.ebayimg.com/00/s/GRWTgrgGrg=/z/T$AWAF87HJ897hjh/$_2.JPG","thumbnailUrl":"https://i.ebayimg.com/00/s/GRWTgrgGrg=/z/AWAF87HJ897hjh/$_14.JPG"}
Image Upload success on try #1
{"status":"OK","thumbnailUrl":"https://i.ebayimg.com/00/s/OKgioGOIJg=/z/JF657tfJFgu54y/$_14.JPG","normalUrl":"https://i.ebayimg.com/00/s/OKgioGOIJg=/z/JF657tfJFgu54y/$_2.JPG"}
Image Upload success on try #1
➜  kijiji_repost_headless git:(master) ✗ 
```

**Comment by vipertemp** [comment]
I get the exact same issue. Occasionally there's a 401 error when uploading the image, but sometimes it just works. It's random and inconsistent.

**Comment by orditeck** [comment]
Probably because the way the token is extracted isn't 100% reliable. The token is already expired before we use it.

**Comment by guoarthur** [comment]
Would any of you like to fix this? I'm quite busy for the next 2 weeks so this one's probably going to have to wait for a while.

**Comment by vipertemp** [comment]
I don't know how any of this token stuff works, or when they expire (or why), or how to fix that sort of thing.

**Comment by guoarthur** [comment]
Are any of you still having this problem? It seems to be working from my logs.

**Comment by orditeck** [comment]
Nop. Didn't have this issue in the last few days. Maybe it was a bug on Kijiji's side.

**Comment by vipertemp** [comment]
Yes, I am and have been since day 1. No changes I make seem to have any positive effect. At random, no matter what I set the sleep delay to, etc, I get this error still.

**Comment by orditeck** [comment]
Just had the issue again.

**Comment by crowbarsolutions** [comment]
Also getting 401 errors. Roughly a 50% chance it will happen when posting. I can have back to back postings and some will get it, others not.

**Comment by justinwrightit** [comment]
@crowbarsolutions Do your ads still post after the 401 errors? I haven't had one this week.

**Comment by crowbarsolutions** [comment]
The ad will post successfully, but there won't be any images attached to the ad.

I get the following from the output:

401
Image Upload failed on try #1
401
Image Upload failed on try #2
401
Image Upload failed on try #3

I can have other postings with images immediately after succeed.

**Comment by rodolpheg** [comment]
I'm having the same problem since I started using the API last week...

PS. until this is fixed, thanks a lot for great work, this API is extremely useful.

**Comment by EmRav** [comment]
I have the same issue with random 401 errors. It can work the first time or sometimes take 3 tries to repost with images. The ad will upload still but there will be no images.

401
Image Upload failed on try #1
401
Image Upload failed on try #2
401
Image Upload failed on try #3

I am a programmer so if you can give me some insight into how the tokens work I would be happy to help as well. I wonder if the token becomes invalid before the upload?

I have 5 different ads right now, i repost them all from folders using the batch script below and a custom C# program that runs any batch script called repost.bat, it waits for the batch script to exit successfully then moves on to the next one. Sometimes all 5 post properly somtimes 3 or more are missing images. Only one script runs at a time as it seems like if I try to repost multiple ones at once then the image issue is worse.

Batch script example:
K:
cd K:\
RMDIR /S /Q K:\kijiji_repost_headless\__pycache__
python kijiji_repost_headless repost_folder KIJIJI-ADS/2-C137
exit

If you need any info I am happy to take a look at the code or debug things with Fiddler when time permits. I have minor python experience but 5+ professional industry experience years and 15+ just from personal experience.

**Comment by justinwrightit** [comment]
When you remove the token from the headers in the post in upload_image(), the 401 error is given. Lead me to believe when upload fails either the token wasn't being passed - it was.. The token being passed in the headers is the right token even when we get the 401 error. Sometimes the 2nd or 3rd attempts work (so even though the page isn't being reloaded, the same token is being passed for the following upload attempts & can work).

Seems like every time i sit down to troubleshoot this I stop getting the error.

**Comment by EmRav** [comment]
Any way just to increase the failure timeout so it doesn't get posted at all without images and starts everything over?

Cheers,

Adam
________________________________

**Comment by guoarthur** [comment]
Can someone try compressing an image to < 1MB and checking if that helps?

**Comment by vipertemp** [comment]
Image size does not seem to affect the probability of encountering this error.

**Comment by EmRav** [comment]
If i try to repost multiple ads at once all in different command prompts then almost always only 1 of the ads will have images. The others will fail to post images if that helps.

**Comment by kjrose** [comment]
Anyone find any form of workaround? Is this Kijiji throttling the calls?

**Comment by rodolpheg** [comment]
@ArthurG All my images are between 38k and 120k, and I get an upload success rate of about 50%. Some images will go through one day and raise an error another... Very strange.

**Comment by Tontiwisk** [comment]
I have a workaround that is perfect for me! 

Instead of trying to post an image with the same token 3 times, I create a new session and get a new token if it fails, and then try again. It eventually works after a couple tries at most. Disclaimer: my code probably doesn't work if you have more than one picture, but I only ever have one. 

I replaced the first bit of the `post_ad_using_data` with:

```
def post_ad_using_data(self, data, image_files=[]):
        """
        Post new ad

        'data' is a dictionary of ad data that to be posted
        'image_files' is a list of binary objects corresponding to images to upload
        """
        image_urls = []
        image_upload_url = 'https://www.kijiji.ca/p-upload-image.html'
        for img_file in image_files:
            for i in range(0, 10):
                # Load ad posting page
                resp = self.session.get('https://www.kijiji.ca/p-admarkt-post-ad.html?categoryId=773')

                #Get tokens required for upload
                token_regex = r"initialXsrfToken: '\S+'"
                image_upload_token = re.findall(token_regex, resp.text)[0].strip("initialXsrfToken: '").strip("'")

                files = {'file': img_file}
                r = self.session.post(image_upload_url, files=files, headers={"x-ebay-box-token": image_upload_token})
                if (r.status_code != 200):
                    print(r.status_code)
                try:
                    image_tree = json.loads(r.text)
                    img_url = image_tree['thumbnailUrl']
                    print("Image Upload success on try #{}".format(i+1))
                    image_urls.append(img_url)
                    break
                except (KeyError, ValueError) as e:
                    print("Image Upload failed on try #{}".format(i+1))
        imageList = [image for image in image_urls if image is not None]

        data['images'] = ",".join(imageList)
```

**Comment by jackm** [comment]
@Tontiwisk it's not obvious what you've changed in your workaround. If it's something that you think fixes a bug, then you can always make a PR with your changes.

**Comment by jackm** [comment]
FWIW I have not had any exceptions occur for me while uploading images during an ad post or repost since around the end of November 2017. This was long before @Tontiwisk proposed fix which I haven't used myself.

I believe that it might have been commit e64a478b09842d55be64a7cf7badb83ac3eb6493 that "fixed" the problem. ...or maybe it was just a coincidence and Kijiji themselves changed something around the same time.

Is anyone else still experiencing these exceptions when uploading images?
