### ISSUE TITLE
issue with posting ad with french characters

### ISSUE THREAD

**Issue by vesper8** [guoarthur/Kijiji-Repost-Headless#48]
Hi there, I'm using the very last version and am running into a decoding issue.

I am using French accents in my title/description. I thought that was fixed according to another issue but I'm still having problems.. here's the traceback

```

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/kijiji_post_headless/__main__.py", line 195, in <module>
    main()
  File "/kijiji_post_headless/__main__.py", line 55, in main
    args.function(args)
  File "/kijiji_post_headless/__main__.py", line 87, in post_folder
    post_ad(args)
  File "/kijiji_post_headless/__main__.py", line 94, in post_ad
    [data, imageFiles] = get_inf_details(args.inf_file)
  File "/kijiji_post_headless/__main__.py", line 76, in get_inf_details
    data = {key: val for line in infFileLines for (key, val) in (line.strip().split("="),)}
  File "/kijiji_post_headless/__main__.py", line 76, in <dictcomp>
    data = {key: val for line in infFileLines for (key, val) in (line.strip().split("="),)}
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 736: ordinal not in range(128)
```

i'm using python3. I thought python3 handles UTF8 decoding better than before as it's built-in to str function now? but I see that on line 76 where the problem is occuring
`data = {key: val for line in infFileLines for (key, val) in (line.strip().split("="),)}`
you are doing some kind of direct assignment which may cause the problem?

another thing I noticed with the latest version is that after it's done uploading a new ad (when using a folder to post at least) it doesn't exit.. it just hangs there and I have to ctrl-c to get out

and lastly as others have reported I'm also getting a lot of random 401s and failed image.. but it works like 75% of the time

**Comment by vesper8** [comment]
managed to figure out the problem

posting with french accents works fine if run from the command line, but the thing is I am calling the python script through php's exec() command and when that happens the encoding is set wrong.. presumably the encoding is set to ascii instead of utf-8

I tried a lot of things to try and "force" the utf-8 encoding including adding
```
#!/usr/bin/python
# -*- coding: utf-8 -*-
```
at the top of the __main__.py file and also trying to set the PYTHONIOENCODING=utf8 before calling the script, but none of those worked

finally I got it all to work by adding encoding ='utf-8' as a 3rd argument in the file open() handles

so `for line in open(args.inf_file, 'rt'):` instead of `for line in open(args.inf_file, 'rt', encoding ='utf-8'):`

I had to add this in a few places but now my french titles and descriptions are posting correctly yay!

as for the script "hanging" after posting an ad.. figured out that's because of a new sleep(180) that was added in the post_ad function. I don't understand its purpose.. it should only be in the repost_ad no? anyway I commented that out and now all is good

still getting 401s on images but I guess that's just Kijiji being temperamental
